### ISSUE TITLE
Big annoying error in images and fonts rule (v10)

### ISSUE THREAD

**Issue by Boorj** [leptosia/poi#482]
In [documentation](https://poi.js.org/options.html#image) we have "Use `filename.image` and `filename.font`". But that doesn't work.
Because of these two guys:
https://github.com/leptosia/poi/blob/v10/packages/core/rules/image.js#L8
https://github.com/leptosia/poi/blob/v10/packages/core/rules/font.js#L8

```js
  config.module
    .rule('image')
    .test([/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/])
  //...
    .options({
      name: filename.images, //... has to be filename.image ( ! ! ! )
    })
```

So that should be changed in documentation for v10

**Comment by egoist** [comment]
ok I merged your doc fix
